### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by jorge-ramirez-arredondo**
update-package-lock action is failing because it seems the committed package-lock.json file wasn't correct? I thought I did this right when I first committed it, but maybe I made a mistake, so I ran npm install again to see if that does it.

image
https://github.com/BrightspaceUI/labs/actions/runs/5193348328/jobs/9363776901

### CODE REVIEW

**Comment by dlockhart** [comment]
This is a known problem with `lit-analyzer` -- in other repos I've just [removed the analyzer entirely](https://github.com/BrightspaceHypermediaComponents/users/pull/156) since it doesn't provide much value anymore.

**Comment by jorge-ramirez-arredondo** [comment]
@dlockhart I noticed in core you [still have lit-analyzer](https://github.com/BrightspaceUI/core/blob/main/package.json#L19). How did you solve this there? Did you just [include typescript 5](https://github.com/BrightspaceUI/core/blob/main/package.json#L70)?

**Comment by dlockhart** [comment]
Yeah we did, but only because core is relying on `lit-analyzer` to generate the `custom-elemens.json` metadata file that the Daylight Site uses. Otherwise I'd remove it.

**Comment by dlockhart** [comment]
Haha, maybe! Ok that makes me want to go and rip it out... brb.

**Comment by jorge-ramirez-arredondo** [comment]
Okay, this PR should no longer be needed now that lit-analyzer has been removed as part of https://github.com/BrightspaceUI/labs/pull/44

**Pull request closed without merging**
